version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: lms-admin
      POSTGRES_PASSWORD: lmspassword123!
    ports:
      - "7002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
